'use strict';

const NEIGHBORHOOD_NAMES = {
  'timnath-ranch': 'Timnath Ranch',
  'serratoga-falls': 'Serratoga Falls',
  'timnath-lakes': 'Timnath Lakes',
  'wildwing': 'Wildwing',
  'trailside': 'Trailside',
  'harmony-club': 'Harmony Club',
};

const NEIGHBORHOODS = [
  {
    name: 'Timnath Ranch',
    slug: 'timnath-ranch',
    metaTitle: 'Exterior Painting in Timnath Ranch | Timnath Painting',
    metaDesc: 'Expert exterior painting for Timnath Ranch homes. HOA color compliance, premium Sherwin-Williams & Benjamin Moore coatings. Free on-site quote. (970) 670-3965.',
    canonical: 'https://timnathpainting.com/neighborhoods/timnath-ranch/',
    heroTitle: 'Exterior Painting in Timnath Ranch',
    tagline: "One of Timnath's largest established communities — fiber cement homes with strict HOA color standards.",
    intro: [
      "Timnath Ranch is one of the largest and most established master-planned communities in Timnath. Developed through the 2010s and 2020s, the neighborhood is built primarily around HardiePlank fiber cement siding — a durable material that holds paint well when properly primed and coated, but shows chalking and color fade clearly after 5–7 years on Colorado's south and west exposures.",
      "The HOA architectural standards in Timnath Ranch are specific: paint colors must come from an approved palette, all changes require documentation submitted to the architectural review committee, and approval timelines typically run 2–4 weeks. We handle that process from start to finish — color samples, documentation, and submission — so homeowners don't get stuck waiting on paperwork.",
    ],
    whoWeServe: "Timnath Ranch homeowners typically come to us when builder-grade coatings start showing their age — chalking trim, faded field colors, or edge failures around garage trim and south-facing fascia. We also work with residents who are preparing to sell and want the exterior refreshed to match current HOA standards.",
    localNote: "Timnath Ranch homes are spread across a large footprint east of I-25, with most properties positioned to face southeast — which means significant UV loading on east-facing front elevations. We schedule first coats on east-facing surfaces in the afternoon and apply south/west exposures in the morning to avoid heat blistering.",
    faqs: [
      { q: 'Does Timnath Ranch HOA require pre-approval for exterior paint colors?', a: 'Yes. Timnath Ranch requires written approval from the architectural review committee before any exterior color change. We provide color samples from the approved palette, prepare the documentation, and submit to the ARC on your behalf. Approvals typically take 2–4 weeks and we build that window into every project timeline.' },
      { q: 'What exterior paint products work best on HardiePlank siding in Timnath Ranch?', a: "Sherwin-Williams Duration and Benjamin Moore Aura are both rated for fiber cement siding and Colorado's Zone 5b freeze-thaw environment. Both carry 7–10 year system lifespans when applied over a proper primer with full surface prep. We use one of these two products on every Timnath Ranch project." },
      { q: 'How long does an exterior paint job last in Timnath Ranch?', a: 'Builder-grade coatings typically fail in 4–6 years on fiber cement in this climate. Premium coatings with proper prep — full wash, caulk, spot prime, two-coat application — last 7–10 years. South and west exposures on Timnath Ranch homes get a third coat as standard practice on our projects.' },
      { q: 'Can you match the existing approved color on my Timnath Ranch home?', a: 'Yes. We use spectrophotometer color matching and coordinate directly with Sherwin-Williams and Benjamin Moore reps to replicate your existing approved color precisely. This is important for touch-ups, partial repaints, and any work that needs to blend with existing surfaces.' },
    ],
    relatedNeighborhoods: ['serratoga-falls', 'timnath-lakes', 'wildwing', 'trailside', 'harmony-club'],
  },
  {
    name: 'Serratoga Falls',
    slug: 'serratoga-falls',
    metaTitle: 'Exterior Painting in Serratoga Falls, Timnath CO | Timnath Painting',
    metaDesc: 'Exterior painting for Serratoga Falls homes in Timnath. HOA-compliant prep, Sherwin-Williams & Benjamin Moore coatings, free on-site quote. (970) 670-3965.',
    canonical: 'https://timnathpainting.com/neighborhoods/serratoga-falls/',
    heroTitle: 'Exterior Painting in Serratoga Falls',
    tagline: 'New construction neighborhood bordering Kitchel Lake — premium homes built by St. Aubyn and TrüMark.',
    intro: [
      "Serratoga Falls is one of Timnath's newest and most upscale neighborhoods, built primarily by St. Aubyn Homes and TrüMark Homes on the west and south shores of Kitchel Lake. Homes here are larger, newer, and priced at the premium end of the Timnath market — with HOA standards to match.",
      "The proximity to Kitchel Lake means Serratoga Falls homes experience more humidity cycling than neighborhoods farther from water. Paint systems on lake-facing elevations face accelerated moisture exposure in spring and fall, which creates adhesion stress on surfaces that weren't properly primed or prepped at the builder stage. We assess moisture exposure as part of every pre-project inspection here.",
    ],
    whoWeServe: "Serratoga Falls homeowners most often contact us 5–7 years after move-in, when builder-applied coatings on north and lake-facing elevations show the first signs of failure — peeling trim, color shift on fiber cement body panels, or caulk separation around windows. We also serve residents needing HOA color updates as palettes are revised by the ARC.",
    localNote: "Lake-adjacent homes in Serratoga Falls accumulate algae and mildew on north and east elevations faster than interior Timnath neighborhoods. Our standard pressure wash protocol uses a mildewcide additive on all north-facing surfaces in this neighborhood — this is not optional on any Serratoga Falls project.",
    faqs: [
      { q: 'Do lake-facing homes in Serratoga Falls need special exterior paint prep?', a: 'Yes. Moisture cycling near Kitchel Lake accelerates mildew growth on north and east elevations. We apply a mildewcide wash during surface prep on all lake-adjacent homes and use elastomeric caulk with mold inhibitors on all joint work. Skipping this step on a Serratoga Falls home will result in early mildew re-growth under the new coating.' },
      { q: 'How long does new construction paint last in Serratoga Falls?', a: 'Builder-grade coatings applied at time of construction typically show chalk, fade, and edge failures by year 5–6 in this climate — sometimes sooner on north and lake-facing elevations due to moisture exposure. Premium repaints using Sherwin-Williams Duration or Benjamin Moore Aura with full prep last 7–10 years.' },
      { q: 'Who approves exterior color changes in Serratoga Falls?', a: 'The Serratoga Falls HOA architectural review committee (ARC) approves all exterior color changes. We handle the full submission process — color selection from the approved palette, written request, and documentation — and build the approval window into your project timeline so there are no delays.' },
      { q: 'Can you paint multi-unit attached homes in Serratoga Falls?', a: 'Yes. Serratoga Falls includes attached townhome-style units along the lakefront. We sequence these projects unit-by-unit with proper masking at shared wall transitions to prevent color bleed and maintain a consistent finish across the row.' },
    ],
    relatedNeighborhoods: ['timnath-ranch', 'timnath-lakes', 'wildwing', 'trailside', 'harmony-club'],
  },
  {
    name: 'Timnath Lakes',
    slug: 'timnath-lakes',
    metaTitle: 'Exterior Painting in Timnath Lakes | Timnath Painting',
    metaDesc: 'Exterior painting specialists for Timnath Lakes homes. HOA color compliance, lake-adjacent prep, premium coatings. Free quote. (970) 670-3965.',
    canonical: 'https://timnathpainting.com/neighborhoods/timnath-lakes/',
    heroTitle: 'Exterior Painting in Timnath Lakes',
    tagline: 'Waterfront-adjacent community with open space corridors and newer single-family construction.',
    intro: [
      "Timnath Lakes is one of Timnath's water-adjacent communities, developed alongside the town's extensive reservoir and open space system. Homes here sit close to open sky and water — which in Northern Colorado means two things for exterior paint: strong UV exposure with minimal surrounding shade, and humidity cycling from the reservoir that accelerates moisture movement in and out of wood trim and fiber cement panels.",
      "Paint systems in Timnath Lakes need to be built for both conditions simultaneously. We use elastomeric coatings on all trim joints, three-coat application on south and west-facing elevations, and mildewcide additive on north-facing surfaces on every project in this neighborhood.",
    ],
    whoWeServe: "Timnath Lakes homeowners typically contact us after noticing chalking on south-facing body panels, peeling on window trim, or mildew spotting on north-facing siding. We also handle HOA-required repaints when the community cycles to new approved palettes.",
    localNote: "Wind exposure is higher in Timnath Lakes than in more interior neighborhoods due to the open reservoir corridor. We schedule painting away from high-wind forecast windows and avoid application on south-facing surfaces in afternoon when summer thermals push wind across the water. Timing matters for paint adhesion in this neighborhood.",
    faqs: [
      { q: 'What is the biggest exterior paint challenge for Timnath Lakes homes?', a: 'Combined UV exposure and humidity cycling from the reservoir. South-facing surfaces get intense UV load that fades budget paint quickly. North-facing surfaces see elevated moisture and mildew. We address both conditions in our standard prep and coating spec for every Timnath Lakes project.' },
      { q: 'How do you handle mildew on north-facing siding in Timnath Lakes?', a: 'Our pressure wash protocol on north-facing surfaces in lake-adjacent neighborhoods includes a mildewcide additive. We also apply a mold-inhibitor primer on bare or chalked surfaces before topcoating. Without this step, mildew re-grows under the new paint within 2–3 seasons.' },
      { q: 'Do I need HOA approval to repaint my home in Timnath Lakes?', a: "Yes, if you are changing colors. If you are repainting with the same existing approved color, some HOAs waive the formal approval requirement — but confirm with your property manager before starting. We'll advise you during the quote visit on what your specific HOA requires." },
      { q: 'How many coats of paint do south-facing walls need in Timnath Lakes?', a: 'A minimum of three coats on south and west-facing elevations is our standard for Timnath Lakes projects. The UV load at this latitude combined with open-sky exposure fades two-coat systems faster than in shaded neighborhoods. We factor this into every quote upfront — no surprises.' },
    ],
    relatedNeighborhoods: ['timnath-ranch', 'serratoga-falls', 'wildwing', 'trailside', 'harmony-club'],
  },
  {
    name: 'Wildwing',
    slug: 'wildwing',
    metaTitle: 'Exterior Painting in Wildwing, Timnath CO | Timnath Painting',
    metaDesc: 'Exterior painting for Wildwing neighborhood homes in Timnath. HOA-compliant, premium prep, free on-site quote. Call (970) 670-3965.',
    canonical: 'https://timnathpainting.com/neighborhoods/wildwing/',
    heroTitle: 'Exterior Painting in Wildwing',
    tagline: 'Established Timnath neighborhood with mature landscaping and a mix of siding profiles.',
    intro: [
      "Wildwing is one of Timnath's more established neighborhoods, with homes built across a wider range of construction years than the town's newer communities. This matters for exterior painting: older homes in Wildwing may have original builder-grade coatings that are now in their second failure cycle, and some properties have wood or composite siding profiles that require different prep protocols than newer fiber cement construction.",
      "We assess every Wildwing property before quoting — substrate type, current coating condition, exposure orientation, and any existing moisture or adhesion issues. The prep spec for a 15-year-old wood-sided Wildwing home is different from a new HardiePlank build in Timnath Ranch, and we price accordingly.",
    ],
    whoWeServe: "Wildwing homeowners contact us when aging paint starts showing visible failure — peeling on soffits and fascia, color fade on south-facing walls, or caulk failure around windows and doors. Older homes with wood trim see these issues faster than fiber cement construction, and we're equipped to handle both.",
    localNote: "Wildwing's mature tree canopy provides more shade than newer Timnath communities — which reduces UV fade on some north and east-facing surfaces but increases mildew risk on shaded siding. We adjust our prep and primer selection based on the specific sun/shade profile of each home we assess in this neighborhood.",
    faqs: [
      { q: 'Do older Wildwing homes need more prep before painting than newer builds?', a: 'Usually, yes. Homes with multiple layers of existing paint require more scraping, sanding, and priming before a new coating will adhere correctly. We assess every Wildwing home individually — the prep spec is not one-size-fits-all, and the quote reflects actual surface condition rather than a flat rate.' },
      { q: 'What siding types are common in Wildwing?', a: "Wildwing has a mix of older and newer construction. You'll find HardiePlank fiber cement on newer homes, T1-11 plywood and wood siding on older properties, and some vinyl siding. Each requires a different primer and prep protocol. We identify the exact siding type during the pre-project inspection and spec accordingly." },
      { q: 'Can you match existing paint colors in Wildwing without HOA documentation?', a: "If you're repainting with the same color and your HOA doesn't require approval for same-color repaints, yes. We can spectrophotometer-match your existing color precisely. If you're changing colors in an HOA community, we handle the approval documentation. Ask your property manager which applies to your situation — we'll advise during the quote." },
      { q: 'Does mildew on shaded siding in Wildwing affect exterior painting?', a: 'It does if it\'s not treated before coating. Mildew that\'s painted over will continue growing under the new paint and cause premature adhesion failure. We treat all mildew-affected surfaces with a biocide wash during prep before applying any primer or topcoat.' },
    ],
    relatedNeighborhoods: ['timnath-ranch', 'serratoga-falls', 'timnath-lakes', 'trailside', 'harmony-club'],
  },
  {
    name: 'Trailside',
    slug: 'trailside',
    metaTitle: 'Exterior Painting in Trailside, Timnath CO | Timnath Painting',
    metaDesc: 'Exterior painting for Trailside neighborhood homes in Timnath, CO. Trail-adjacent, HOA-compliant, premium coatings. Free quote. (970) 670-3965.',
    canonical: 'https://timnathpainting.com/neighborhoods/trailside/',
    heroTitle: 'Exterior Painting in Trailside',
    tagline: "Connected to Timnath's trail network — newer construction with open space exposure on multiple elevations.",
    intro: [
      "Trailside is one of Timnath's newer communities, built adjacent to the town's expanding trail corridor and open space network. Homes here are newer construction — primarily fiber cement siding — with many lots backing to or facing open space. That open exposure means less natural shade buffer from surrounding homes, which increases UV load on south and west elevations.",
      "Trail-adjacent properties also see more wind-blown debris and seasonal dust accumulation on north-facing surfaces than interior lots. We factor that into our pressure wash and surface prep on every Trailside project.",
    ],
    whoWeServe: "Trailside homeowners typically contact us 4–7 years after move-in, when builder-grade coatings show first fade on south-facing walls or first caulk failure around windows. We also handle HOA-coordinated repaints when the community updates its approved color palette.",
    localNote: "Homes in Trailside that back to open space experience direct wind loading from the west across undeveloped land. We assess wind exposure during the quote visit and avoid scheduling application on days with forecast gusts above 15 mph — paint applied in high wind conditions develops application defects that compromise long-term adhesion.",
    faqs: [
      { q: 'Why do south-facing walls on Trailside homes fade faster than other elevations?', a: "Open space lots in Trailside have minimal shade buffer from trees or adjacent structures on south-facing walls. Direct UV exposure at this latitude combined with Colorado's altitude (10–15% higher UV than coastal at the same latitude) accelerates pigment fade on budget coatings. We apply three coats on south and west-facing elevations as standard on all Trailside projects." },
      { q: 'Do trail-adjacent homes in Trailside need extra prep for dust and debris?', a: 'Yes. Trail-adjacent lots accumulate significantly more dust, pollen, and fine debris on north and windward-facing surfaces than interior lots. We use a high-pressure wash with a cleaning solution to ensure all contamination is removed before primer application — debris embedded in the surface will cause adhesion failure if not removed.' },
      { q: 'Does the Trailside HOA require color approval before exterior painting?', a: 'Yes. All Timnath HOA communities require architectural review committee approval for exterior color changes. We handle the full documentation and submission process for Trailside homeowners — including color selection from the approved palette, written request preparation, and ARC submission.' },
      { q: 'How far in advance should I book exterior painting in Trailside?', a: 'Spring slots (May–June) fill 4–8 weeks in advance. We recommend booking in March or April for a late spring project. Fall (September–October) is also an excellent painting window in Northern Colorado — cooler temperatures, lower UV, and manageable humidity. Contact us early in the season to lock in your window.' },
    ],
    relatedNeighborhoods: ['timnath-ranch', 'serratoga-falls', 'timnath-lakes', 'wildwing', 'harmony-club'],
  },
  {
    name: 'Harmony Club',
    slug: 'harmony-club',
    metaTitle: 'Exterior Painting in Harmony Club, Timnath CO | Timnath Painting',
    metaDesc: 'Exterior painting for Harmony Club golf course community homes in Timnath. Premium prep, HOA-compliant, free quote. (970) 670-3965.',
    canonical: 'https://timnathpainting.com/neighborhoods/harmony-club/',
    heroTitle: 'Exterior Painting in Harmony Club',
    tagline: "Timnath's premier golf course community — upscale homes with elevated exterior standards.",
    intro: [
      "Harmony Club is Timnath's upscale golf course community, featuring larger and higher-value homes with exterior finishes that are expected to hold up to a higher standard. The community sits along manicured fairways, which means most homes have significant open-sky exposure — strong UV loading, wind across open turf, and the irrigation-driven humidity that comes from maintained green space adjacent to your property.",
      "Harmony Club HOA standards are detailed and strictly enforced. Color palettes are curated for the community's aesthetic, approval timelines are non-negotiable, and color consistency across the community is a governance priority. We have worked with HOA communities of this caliber and understand what it takes to meet those standards — from documentation to application precision.",
    ],
    whoWeServe: "Harmony Club homeowners contact us when premium builder finishes start showing their age — typically at the 5–8 year mark on south and fairway-facing elevations. We also serve property owners who are preparing a home for sale and need the exterior to be at Harmony Club aesthetic standard, and HOA boards coordinating community-wide repaints.",
    localNote: "Golf course irrigation creates a significant humidity differential between the fairway side of a Harmony Club home and the street side. Fairway-facing elevations see more moisture cycling — especially in summer when irrigation runs daily — which increases the risk of early adhesion failure if surfaces aren't primed with moisture-tolerant products. We assess irrigation exposure during every Harmony Club quote visit and spec accordingly.",
    faqs: [
      { q: 'How strict is the Harmony Club HOA about exterior paint color approval?', a: 'Very strict. Harmony Club maintains a curated color palette and enforces HOA standards through the architectural review committee. Any exterior color change requires ARC approval with color samples and written documentation before work begins. We handle the entire process — color selection, sample submission, documentation, and ARC coordination — from quote to approval.' },
      { q: 'Do fairway-facing walls in Harmony Club need special prep?', a: 'Yes. Irrigation from adjacent fairways creates consistent moisture loading on fairway-facing elevations, especially in summer. We use elastomeric primer with moisture-barrier properties on fairway-facing walls and apply mildewcide treatment as standard. Skipping this step on a golf-course-adjacent home leads to early mildew growth and coating adhesion failure.' },
      { q: 'How long does a premium exterior paint job last on a Harmony Club home?', a: 'With full prep — pressure wash, caulk, prime, two-coat minimum on all surfaces, three coats on south and fairway-facing elevations — Sherwin-Williams Duration and Benjamin Moore Aura systems last 7–10 years on Harmony Club homes. Builder-grade coatings typically fail at year 5–6, often sooner on south-facing and irrigation-adjacent elevations.' },
      { q: 'Can you match the original builder color on my Harmony Club home exactly?', a: "Yes. We use spectrophotometer color matching and work with Sherwin-Williams and Benjamin Moore contractor reps to replicate existing colors with precision. This is critical in Harmony Club, where color consistency across adjacent properties is an HOA governance priority. A near-match is not acceptable — we get it right." },
    ],
    relatedNeighborhoods: ['timnath-ranch', 'serratoga-falls', 'timnath-lakes', 'wildwing', 'trailside'],
  },
];

module.exports = { NEIGHBORHOODS, NEIGHBORHOOD_NAMES };
